import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
    translation: {
      shop: "Shop by Region",
      categories: "Categories",
      artisans: "Artisans",
      reviews: "Reviews",
      login: "Login",
      signup: "Sign Up",
      logout: "Logout",
      filter: "Filter",
      south: "South India",
      north: "North India",

      southIndiaFabrics: "South India Fabrics",
      northIndiaFabrics: "North India Fabrics",

      andhraPradesh: "Andhra Pradesh",
      tamilNadu: "Tamil Nadu",
      karnataka: "Karnataka",
      kerala: "Kerala",
      telangana: "Telangana",
      uttarPradesh: "Uttar Pradesh",
      rajasthan: "Rajasthan",
      punjab: "Punjab",
      madhyaPradesh: "Madhya Pradesh",
      kashmir: "Kashmir",

      mangalagiri: "Mangalagiri",
      pochampallyIkat: "Pochampally Ikat",
      kalamkari: "Kalamkari",
      kanchipuramSilk: "Kanchipuram Silk",
      chettinadCotton: "Chettinad Cotton",
      mysoreSilk: "Mysore Silk",
      ilkalSaree: "Ilkal Saree",
      kasavuSaree: "Kasavu Saree",
      gadwalSaree: "Gadwal Saree",
      banarasiSilk: "Banarasi Silk",
      bandhani: "Bandhani",
      leheriya: "Leheriya",
      phulkari: "Phulkari",
      chanderi: "Chanderi",
      maheshwari: "Maheshwari",
      pashminaWool: "Pashmina Wool",
      products: "Products",
      mangalagiriKurtasetFabric: "Mangalagiri Kurtaset Fabric",
mangalagiriHandloomSaree: "Mangalagiri Handloom Saree",

from: "from",
addToCart: "Add to Cart",
 pochampallyIkatSaree: "Pochampally Ikat Saree",
 pochampallyFrock: "Pochampally Frock",
 products: "Products",
from: "from",
addToCart: "Add to Cart",
mangalagiriKurtasetFabric: "Mangalagiri Kurtaset Fabric",
mangalagiriHandloomSaree: "Mangalagiri Handloom Saree",
pochampallyIkatSaree: "Pochampally Ikat Saree",
pochampallyFrock: "Pochampally Frock",
"pochampally-ikat": "Pochampally Ikat",
buyNow: "Buy Now",

launch: "Just Launched",
from: "from",
cart: "Add to cart",

goldenThreads: "Golden Threads",
mangalagiriKurtiSet: "Mangalagiri Kurti Set",
snowBag: "Snow Bag",
pillowCover: "Pillow Cover",
buyNow: "Buy Now",

buyNow: "Buy Now",
checkout: "Checkout",
price: "Price",
delivery: "Delivery",
freeDelivery: "Free Delivery",
placeOrder: "Place Order",
orderPlaced: "Order placed successfully!",
noProductSelected: "No product selected",
goHome: "Go Home",
supportTitle: "Support Our Artisans",
supportDesc1: "Every fabric you see is crafted with love by skilled weavers across India.",
supportDesc2: "By purchasing these products, you are helping preserve traditional handloom art and supporting the livelihood of artisans.",
supportDesc3: "Your support keeps these beautiful traditions alive.",
 addedToCart: "Successfully added to cart",
 yourCart: "Your Cart",
emptyCart: "Your cart is empty",
buyNow: "Buy Now",
remove: "Remove",



    },
  },

  te: {
    translation: {
      shop: "ప్రాంతం ప్రకారం కొనండి",
      categories: "వర్గాలు",
      artisans: "కార్మికులు",
      reviews: "సమీక్షలు",
      login: "లాగిన్",
      signup: "సైన్ అప్",
      logout: "లాగౌట్",
      filter: "ఫిల్టర్",
      south: "దక్షిణ భారతదేశం",
      north: "ఉత్తర భారతదేశం",

      southIndiaFabrics: "దక్షిణ భారత వస్త్రాలు",
      northIndiaFabrics: "ఉత్తర భారత వస్త్రాలు",

      andhraPradesh: "ఆంధ్రప్రదేశ్",
      tamilNadu: "తమిళనాడు",
      karnataka: "కర్ణాటక",
      kerala: "కేరళ",
      telangana: "తెలంగాణ",
      uttarPradesh: "ఉత్తరప్రదేశ్",
      rajasthan: "రాజస్థాన్",
      punjab: "పంజాబ్",
      madhyaPradesh: "మధ్యప్రదేశ్",
      kashmir: "కాశ్మీర్",

      mangalagiri: "మంగళగిరి",
      pochampallyIkat: "పోచంపల్లి ఇక్కత్",
      kalamkari: "కలంకారి",
      kanchipuramSilk: "కాంచీపురం సిల్క్",
      chettinadCotton: "చెట్టినాడ్ కాటన్",
      mysoreSilk: "మైసూర్ సిల్క్",
      ilkalSaree: "ఇల్కల్ చీర",
      kasavuSaree: "కసావు చీర",
      gadwalSaree: "గద్వాల్ చీర",
      banarasiSilk: "బనారసీ సిల్క్",
      bandhani: "బంధనీ",
      leheriya: "లెహేరియా",
      phulkari: "ఫుల్కారి",
      chanderi: "చందేరి",
      maheshwari: "మహేశ్వరి",
      pashminaWool: "పష్మీనా వూల్",
      products: "ఉత్పత్తులు",
      mangalagiriKurtasetFabric: "మంగళగిరి కుర్తా సెట్ ఫ్యాబ్రిక్",
mangalagiriHandloomSaree: "మంగళగిరి హ్యాండ్లూమ్ చీర",
products: "ఉత్పత్తులు",
from: "నుండి",
addToCart: "కార్ట్‌లో జోడించండి",
pochampallyIkatSaree: "పొచంపల్లి ఇకట్ చీర",
pochampallyFrock: "పోచంపల్లి ఫ్రాక్",

launch: "కొత్తగా విడుదలైనవి",
from: "నుండి",
cart: "కార్ట్‌లో జోడించండి",

goldenThreads: "గోల్డెన్ థ్రెడ్స్",
mangalagiriKurtiSet: "మంగళగిరి కుర్తి సెట్",
snowBag: "స్నో బ్యాగ్",
pillowCover: "పిల్లో కవర్",
buyNow: "ఇప్పుడే కొనండి",

buyNow: "ఇప్పుడే కొనండి",
checkout: "చెల్లింపు",
price: "ధర",
delivery: "డెలివరీ",
freeDelivery: "ఉచిత డెలివరీ",
placeOrder: "ఆర్డర్ చేయండి",
orderPlaced: "ఆర్డర్ విజయవంతంగా పూర్తైంది!",
noProductSelected: "ఏ ఉత్పత్తి ఎంపిక చేయలేదు",
goHome: "హోమ్‌కు వెళ్ళండి",
supportTitle: "మన కళాకారులను మద్దతు ఇవ్వండి",
supportDesc1: "మీరు చూస్తున్న ప్రతి వస్త్రం భారతదేశంలోని నైపుణ్యం గల నేయకారుల చేత ప్రేమతో తయారవుతుంది.",
supportDesc2: "ఈ ఉత్పత్తులను కొనుగోలు చేయడం ద్వారా మీరు సంప్రదాయ హ్యాండ్‌లూమ్ కళను కాపాడడంలో సహాయపడుతున్నారు.",
supportDesc3: "మీ మద్దతు ఈ అందమైన సంప్రదాయాలను కొనసాగిస్తుంది.",
addedToCart: "కార్ట్‌లో విజయవంతంగా జోడించబడింది",
 yourCart: "మీ కార్ట్",
emptyCart: "మీ కార్ట్ ఖాళీగా ఉంది",
buyNow: "ఇప్పుడే కొనండి",
remove: "తొలగించండి",









    },
  },

  hi: {
    translation: {
      shop: "क्षेत्र के अनुसार खरीदें",
      categories: "श्रेणियाँ",
      artisans: "कारीगर",
      reviews: "समीक्षाएं",
      login: "लॉगिन",
      signup: "साइन अप",
      logout: "लॉगआउट",
      filter: "फ़िल्टर",
      south: "दक्षिण भारत",
      north: "उत्तर भारत",

      southIndiaFabrics: "दक्षिण भारत के वस्त्र",
      northIndiaFabrics: "उत्तर भारत के वस्त्र",

      andhraPradesh: "आंध्र प्रदेश",
      tamilNadu: "तमिलनाडु",
      karnataka: "कर्नाटक",
      kerala: "केरल",
      telangana: "तेलंगाना",
      uttarPradesh: "उत्तर प्रदेश",
rajasthan: "राजस्थान",
madhyaPradesh: "मध्य प्रदेश",
kashmir: "कश्मीर",

      mangalagiri: "मंगलागिरि",
      banarasiSilk: "बनारसी सिल्क",
      pochampallyIkat: "पोचमपल्ली इकट",
      kalamkari: "कलमकारी",
      kanchipuramSilk: "कांचीपुरम सिल्क",
      chettinadCotton: "चेट्टिनाड कॉटन",
      mysoreSilk: "मैसूर सिल्क",
      ilkalSaree: "इलकल साड़ी",
      kasavuSaree: "कसावु साड़ी",
      gadwalSaree: "गडवाल साड़ी",
      banarasiSilk: "बनारसी सिल्क",
bandhani: "बंधनी",
leheriya: "लहरिया",
phulkari: "फुलकारी",
chanderi: "चंदेरी",

pashminaWool: "पश्मीना ऊन",

products: "उत्पाद",
from: "से",
addToCart: "कार्ट में जोड़ें",
mangalagiriKurtasetFabric: "मंगलागिरि कुर्ता सेट फैब्रिक",
mangalagiriHandloomSaree: "मंगलागिरि हैंडलूम साड़ी",
products: "उत्पाद",
from: "से",
addToCart: "कार्ट में जोड़ें",
mangalagiriKurtasetFabric: "मंगलागिरि कुर्ता सेट फैब्रिक",
mangalagiriHandloomSaree: "मंगलागिरि हैंडलूम साड़ी",
pochampallyIkatSaree: "पोचमपल्ली इकट साड़ी",
pochampallyFrock: "पोचमपल्ली फ्रॉक",
"pochampally-ikat": "पोचमपल्ली इकट",
buyNow: "अभी खरीदें",

launch: "अभी लॉन्च हुआ",
from: "से",
cart: "कार्ट में जोड़ें",

goldenThreads: "गोल्डन थ्रेड्स",
mangalagiriKurtiSet: "मंगलागिरि कुर्ती सेट",
snowBag: "स्नो बैग",
pillowCover: "पिलो कवर",
buyNow: "अभी खरीदें",

buyNow: "अभी खरीदें",
checkout: "चेकआउट",
price: "कीमत",
delivery: "डिलीवरी",
freeDelivery: "मुफ्त डिलीवरी",
placeOrder: "ऑर्डर करें",
orderPlaced: "ऑर्डर सफलतापूर्वक हो गया!",
noProductSelected: "कोई उत्पाद चयनित नहीं है",
goHome: "होम पर जाएँ",

supportTitle: "हमारे कारीगरों का समर्थन करें",
supportDesc1: "आप जो भी कपड़े देखते हैं, वे पूरे भारत के कुशल बुनकरों द्वारा प्रेम से बनाए जाते हैं।",
supportDesc2: "इन उत्पादों को खरीदकर आप पारंपरिक हैंडलूम कला को संरक्षित करने और कारीगरों की आजीविका का समर्थन करने में मदद कर रहे हैं।",
supportDesc3: "आपका समर्थन इन सुंदर परंपराओं को जीवित रखता है।",
addedToCart: "कार्ट में सफलतापूर्वक जोड़ा गया",
yourCart: "आपका कार्ट",
emptyCart: "आपका कार्ट खाली है",
buyNow: "अभी खरीदें",
remove: "हटाएं",


    },
  },

  ta: {
    translation: {
      shop: "பகுதி அடிப்படையில் வாங்குங்கள்",
      categories: "வகைகள்",
      artisans: "கலைஞர்கள்",
      reviews: "மதிப்புரைகள்",
      login: "உள்நுழை",
      signup: "பதிவு செய்",
      logout: "வெளியேறு",
      filter: "வடிகட்டி",
      south: "தென் இந்தியா",
      north: "வட இந்தியா",
      southIndiaFabrics: "தென் இந்திய துணிகள்",
      northIndiaFabrics: "வட இந்திய துணிகள்",
      andhraPradesh: "ஆந்திரப் பிரதேசம்",
tamilNadu: "தமிழ்நாடு",
karnataka: "கர்நாடகா",
kerala: "கேரளா",
telangana: "தெலங்கானா",
uttarPradesh: "உத்தரப் பிரதேசம்",
rajasthan: "ராஜஸ்தான்",
punjab: "பஞ்சாப்",
madhyaPradesh: "மத்தியப் பிரதேசம்",
kashmir: "காஷ்மீர்",

mangalagiri: "மங்களகிரி",
pochampallyIkat: "போச்சம்பள்ளி இக்கட்",
kalamkari: "கலம்காரி",
kanchipuramSilk: "காஞ்சிபுரம் சில்க்",
chettinadCotton: "செட்டிநாடு காட்டன்",
mysoreSilk: "மைசூர் சில்க்",
ilkalSaree: "இல்கல் சேலை",
kasavuSaree: "கசாவு சேலை",
gadwalSaree: "கட்வால் சேலை",
banarasiSilk: "பனாரசி சில்க்",

bandhani: "பந்தனி",
leheriya: "லெஹேரியா",
phulkari: "புல்காரி",
chanderi: "சந்தேரி",
maheshwari: "மகேஷ்வரி",
pashminaWool: "பஷ்மினா ஊல்",

launch: "புதிய வரவுகள்",
from: "முதல்",
cart: "வண்டியில் சேர்",

goldenThreads: "கோல்டன் த்ரெட்ஸ்",
mangalagiriKurtiSet: "மங்களகிரி குர்த்தி செட்",
snowBag: "ஸ்னோ பை",
pillowCover: "தலையணை உறை",
buyNow: "இப்போது வாங்குங்கள்",

supportTitle: "எங்கள் கலைஞர்களை ஆதரிக்கவும்",
supportDesc1: "நீங்கள் பார்க்கும் ஒவ்வொரு துணியும் இந்தியா முழுவதும் உள்ள திறமையான நெசவாளர்களால் அன்புடன் உருவாக்கப்படுகிறது.",
supportDesc2: "இந்த தயாரிப்புகளை வாங்குவதன் மூலம் பாரம்பரிய கைத்தறி கலையை பாதுகாக்கவும் கலைஞர்களின் வாழ்வாதாரத்தை ஆதரிக்கவும் உதவுகிறீர்கள்.",
supportDesc3: "உங்கள் ஆதரவு இந்த அழகான பாரம்பரியங்களை உயிருடன் வைத்திருக்கிறது.",


      
    },
  },

  kn: {
    translation: {
      shop: "ಪ್ರದೇಶದ ಆಧಾರದ ಮೇಲೆ ಖರೀದಿಸಿ",
      categories: "ವರ್ಗಗಳು",
      artisans: "ಕಾರಿಗರು",
      reviews: "ವಿಮರ್ಶೆಗಳು",
      login: "ಲಾಗಿನ್",
      signup: "ಸೈನ್ ಅಪ್",
      logout: "ಲಾಗ್ ಔಟ್",
      filter: "ಫಿಲ್ಟರ್",
      south: "ದಕ್ಷಿಣ ಭಾರತ",
      north: "ಉತ್ತರ ಭಾರತ",
      southIndiaFabrics: "ದಕ್ಷಿಣ ಭಾರತದ ವಸ್ತ್ರಗಳು",
      northIndiaFabrics: "ಉತ್ತರ ಭಾರತದ ವಸ್ತ್ರಗಳು",
      andhraPradesh: "ಆಂಧ್ರ ಪ್ರದೇಶ",
tamilNadu: "ತಮಿಳುನಾಡು",
karnataka: "ಕರ್ನಾಟಕ",
kerala: "ಕೇರಳ",
telangana: "ತೆಲಂಗಾಣ",
uttarPradesh: "ಉತ್ತರ ಪ್ರದೇಶ",
rajasthan: "ರಾಜಸ್ಥಾನ",
punjab: "ಪಂಜಾಬ್",
madhyaPradesh: "ಮಧ್ಯ ಪ್ರದೇಶ",
kashmir: "ಕಾಶ್ಮೀರ",

mangalagiri: "ಮಂಗಳಗಿರಿ",
pochampallyIkat: "ಪೋಚಂಪಳ್ಳಿ ಇಕಟ್",
kalamkari: "ಕಲಂಕಾರಿ",
kanchipuramSilk: "ಕಾಂಚೀಪುರಂ ಸಿಲ್ಕ್",
chettinadCotton: "ಚೆಟ್ಟಿನಾಡು ಕಾಟನ್",
mysoreSilk: "ಮೈಸೂರು ಸಿಲ್ಕ್",
ilkalSaree: "ಇಲ್ಕಲ್ ಸೀರೆ",
kasavuSaree: "ಕಸಾವು ಸೀರೆ",
gadwalSaree: "ಗದ್ವಾಲ್ ಸೀರೆ",
banarasiSilk: "ಬನಾರಸಿ ಸಿಲ್ಕ್",

bandhani: "ಬಂಧನಿ",
leheriya: "ಲೆಹೇರಿಯಾ",
phulkari: "ಫುಲ್ಕಾರಿ",
chanderi: "ಚಂದೇರಿ",
maheshwari: "ಮಹೇಶ್ವರಿ",
pashminaWool: "ಪಶ್ಮೀನಾ ವೂಲ್",

launch: "ಹೊಸ ಆಗಮನಗಳು",
from: "ಇಂದ",
cart: "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",

goldenThreads: "ಗೋಲ್ಡನ್ ಥ್ರೆಡ್ಸ್",
mangalagiriKurtiSet: "ಮಂಗಳಗಿರಿ ಕುರ್ಥಿ ಸೆಟ್",
snowBag: "ಸ್ನೋ ಬ್ಯಾಗ್",
pillowCover: "ಪಿಲ್ಲೋ ಕವರ್",
buyNow: "ಈಗ ಖರೀದಿಸಿ",

supportTitle: "ನಮ್ಮ ಕಲಾವಿದರನ್ನು ಬೆಂಬಲಿಸಿ",
supportDesc1: "ನೀವು ನೋಡುವ ಪ್ರತಿಯೊಂದು ಬಟ್ಟೆಯೂ ಭಾರತದಾದ್ಯಂತದ ನಿಪುಣ ನೆಯ್ಗಾರರಿಂದ ಪ್ರೀತಿಯಿಂದ ತಯಾರಿಸಲಾಗುತ್ತದೆ.",
supportDesc2: "ಈ ಉತ್ಪನ್ನಗಳನ್ನು ಖರೀದಿಸುವುದರಿಂದ ನೀವು ಪರಂಪರাগত ಹ್ಯಾಂಡ್‌ಲೂಮ್ ಕಲೆಯನ್ನು ಉಳಿಸಿ ಕಲಾವಿದರ ಜೀವನೋಪಾಯಕ್ಕೆ ಬೆಂಬಲ ನೀಡುತ್ತೀರಿ.",
supportDesc3: "ನಿಮ್ಮ ಬೆಂಬಲವು ಈ ಸುಂದರ ಪರಂಪರೆಗಳನ್ನು ಜೀವಂತವಾಗಿರಿಸುತ್ತದೆ.",
      
    },
  },

  ml: {
    translation: {
      shop: "പ്രദേശത്തിന്റെ അടിസ്ഥാനത്തിൽ വാങ്ങുക",
      categories: "വിഭാഗങ്ങൾ",
      artisans: "കലാകാരന്മാർ",
      reviews: "അഭിപ്രായങ്ങൾ",
      login: "ലോഗിൻ",
      signup: "സൈൻ അപ്പ്",
      logout: "ലോഗൗട്ട്",
      filter: "ഫിൽട്ടർ",
      south: "ദക്ഷിണ ഇന്ത്യ",
      north: "വടക്കേ ഇന്ത്യ",
      andhraPradesh: "ആന്ധ്ര പ്രദേശ്",
tamilNadu: "തമിഴ്നാട്",
karnataka: "കർണാടക",
kerala: "കേരളം",
telangana: "തെലങ്കാന",
uttarPradesh: "ഉത്തര പ്രദേശ്",
rajasthan: "രാജസ്ഥാൻ",
punjab: "പഞ്ചാബ്",
madhyaPradesh: "മധ്യ പ്രദേശ്",
kashmir: "കാശ്മീർ",

mangalagiri: "മംഗളഗിരി",
pochampallyIkat: "പൊച്ചമ്പള്ളി ഇക്കറ്റ്",
kalamkari: "കലങ്കാരി",
kanchipuramSilk: "കാഞ്ചിപുരം സിൽക്ക്",
chettinadCotton: "ചെട്ടിനാട് കോട്ടൺ",
mysoreSilk: "മൈസൂർ സിൽക്ക്",
ilkalSaree: "ഇൽകൽ സാരി",
kasavuSaree: "കസാവ് സാരി",
gadwalSaree: "ഗദ്വാൽ സാരി",
banarasiSilk: "ബനാരസി സിൽക്ക്",

bandhani: "ബന്ധനി",
leheriya: "ലേഹേറിയ",
phulkari: "ഫുൽക്കാരി",
chanderi: "ചന്ദേരി",
maheshwari: "മഹേശ്വരി",
pashminaWool: "പഷ്മീന വൂൾ",

launch: "പുതിയ വരവുകൾ",
from: "മുതൽ",
cart: "കാർട്ടിൽ ചേർക്കുക",

goldenThreads: "ഗോൾഡൻ ത്രെഡ്സ്",
mangalagiriKurtiSet: "മംഗളഗിരി കുര്തി സെറ്റ്",
snowBag: "സ്നോ ബാഗ്",
pillowCover: "പില്ലോ കവർ",
buyNow: "ഇപ്പോൾ വാങ്ങുക",

supportTitle: "ഞങ്ങളുടെ കലാകാരന്മാരെ പിന്തുണയ്ക്കൂ",
supportDesc1: "നിങ്ങൾ കാണുന്ന ഓരോ വസ്ത്രവും ഇന്ത്യയിലുടനീളം ഉള്ള പ്രാവീണ്യമുള്ള നെയ്ത്തുകാരുടെ സ്നേഹത്തോടെ നിർമ്മിച്ചതാണ്.",
supportDesc2: "ഈ ഉൽപ്പന്നങ്ങൾ വാങ്ങുന്നതിലൂടെ പരമ്പരാഗത കൈത്തറി കലയെ സംരക്ഷിക്കുകയും കലാകാരന്മാരുടെ ജീവിതോപാധിക്ക് പിന്തുണ നൽകുകയും ചെയ്യുന്നു.",
supportDesc3: "നിങ്ങളുടെ പിന്തുണ ഈ മനോഹരമായ പാരമ്പര്യങ്ങളെ ജീവനോടെ നിലനിർത്തുന്നു.",
      
    },
  },

  bn: {
    translation: {
      shop: "অঞ্চল অনুযায়ী কিনুন",
      categories: "বিভাগসমূহ",
      artisans: "কারিগর",
      reviews: "রিভিউ",
      login: "লগইন",
      signup: "সাইন আপ",
      logout: "লগআউট",
      filter: "ফিল্টার",
      south: "দক্ষিণ ভারত",
      north: "উত্তর ভারত",
    },
  },

  mr: {
    translation: {
      shop: "प्रदेशानुसार खरेदी करा",
      categories: "वर्ग",
      artisans: "कारागीर",
      reviews: "पुनरावलोकने",
      login: "लॉगिन",
      signup: "साइन अप",
      logout: "लॉगआउट",
      filter: "फिल्टर",
      south: "दक्षिण भारत",
      north: "उत्तर भारत",
    },
  },

  gu: {
    translation: {
      shop: "પ્રદેશ અનુસાર ખરીદી કરો",
      categories: "વર્ગો",
      artisans: "કારીગરો",
      reviews: "સમીક્ષાઓ",
      login: "લોગિન",
      signup: "સાઇન અપ",
      logout: "લોગઆઉટ",
      filter: "ફિલ્ટર",
      south: "દક્ષિણ ભારત",
      north: "ઉત્તર ભારત",
    },
  },

  pa: {
    translation: {
      shop: "ਖੇਤਰ ਦੇ ਅਨੁਸਾਰ ਖਰੀਦੋ",
      categories: "ਸ਼੍ਰੇਣੀਆਂ",
      artisans: "ਕਾਰੀਗਰ",
      reviews: "ਸਮੀਖਿਆਵਾਂ",
      login: "ਲੌਗਇਨ",
      signup: "ਸਾਈਨ ਅੱਪ",
      logout: "ਲੌਗਆਉਟ",
      filter: "ਫਿਲਟਰ",
      south: "ਦੱਖਣ ਭਾਰਤ",
      north: "ਉੱਤਰ ਭਾਰਤ",
    },
  },
};


i18n.use(initReactI18next).init({
  resources,
  lng: localStorage.getItem("lang") || "en",
  fallbackLng: "en",
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;